// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");

var mapOfInput = Belt_Array.reduce(Fs.readFileSync("./src/input/input_sample.txt", "utf8").split("\n"), undefined, (function (acc, n) {
        return Belt_MapString.set(acc, n, Caml_format.caml_int_of_string(n));
      }));

console.log(mapOfInput);

var res1 = Belt_MapString.reduce(mapOfInput, [
      0,
      0
    ], (function (acc, param, v) {
        var found = Belt_MapString.get(mapOfInput, String(2020 - v | 0));
        if (found !== undefined) {
          return [
                  v,
                  found
                ];
        } else {
          return acc;
        }
      }));

console.log(res1);

var target = 2020;

exports.mapOfInput = mapOfInput;
exports.target = target;
exports.res1 = res1;
/* mapOfInput Not a pure module */
